MPICC?=mpicxx


p1_1: p1_1.cpp
		${MPICC} -o p1_1 p1_1.cpp -lm -std=c++11

p1_2: p1_2.cpp
		${MPICC} -o p1_2 p1_2.cpp -lm -std=c++11

p1_3: p1_3.cpp
		${MPICC} -o p1_3 p1_3.cpp -lm -std=c++11

p2_1: p2_1.cpp
		g++ -o p2_1 p2_1.cpp -fopenmp -std=c++11

p2_2: p2_2.cpp
		g++ -o p2_2 p2_2.cpp -fopenmp -std=c++11

p2_3: p2_3.cpp
		g++ -o p2_3 p2_3.cpp -fopenmp -std=c++11

